name: ' MO:PR'
favicon: null
layout_spectrum: 0.24741
typography_spectrum: 0.13707
title: 'PR for the Québec market '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00b0bf'
    - '#00407d'
    - '#fefefc'
    - '#a6a08d'
  brandStrength: 0.7543617310002446
  lightness: 0.0826674192212522
  saturation: 0.9021336548030376
  rhythmicContrast: 0.8512920446228236
purpose: []
